/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.retosofkau;

import java.util.Iterator;
import javax.swing.JOptionPane;

/**
 *
 * @author PERSONAL
 */
public class CrearNave extends javax.swing.JFrame {
    
    //Se crean variables que se van a usar para almacenar lo que se ponga en el formulario
    String mNombre;
    String mTipo_Nave;
    String mTipo_combustible;
    String mRegion;
    double mPotencia;
    double mEmpuje;
    double mVelocidad;
    double mPeso;
    String mDestino;
    String mTipo_mision;
    int mCapacidad;
    int aux = 0;
    
    
    public CrearNave() {
        initComponents();
        this.setLocationRelativeTo(null);
    }
    
    
    
    public void obtenerDatos(){
        //Se le asignan los valores puestos en el formulario a las variables globales
        mNombre = F_Nombre.getText();
        mTipo_Nave = (String) F_Tipo_nave.getSelectedItem();
        mTipo_combustible = F_Tipo_combustible.getText();
        mRegion = (String) F_Region.getSelectedItem();
        mPotencia = Double.parseDouble(F_Potencia.getText());
        mEmpuje = Double.parseDouble(F_Empuje.getText());
        mVelocidad = Double.parseDouble(F_Velocidad.getText());
        mPeso = Double.parseDouble(F_Peso.getText());
        mDestino = (String) F_Destino.getSelectedItem();
        mTipo_mision = (String) F_Tipo_mision.getSelectedItem();
        mCapacidad = Integer.parseInt(F_Capacidad.getText());

    }
    
    public void guardarDatos(){
        
        //Se crea un objeto de tipo nave, para que contenga todas las caracteristicas de estas
        Nave nuevaNave = new Nave();
        
        //Se guardan los valores que se pusieron en el formulario en las variables de la clase Nave
        nuevaNave.setNombre(mNombre); 
        nuevaNave.setTipo_nave(mTipo_Nave);
        nuevaNave.setTipo_combustible(mTipo_combustible);
        nuevaNave.setRegion(mRegion);
        nuevaNave.setPotencia(mPotencia);
        nuevaNave.setEmpuje(mEmpuje);
        nuevaNave.setVelocidad(mVelocidad);
        nuevaNave.setPeso(mPeso);
        nuevaNave.setDestino(mDestino);
        nuevaNave.setTipo_mision(mTipo_mision);
        nuevaNave.setCapacidad(mCapacidad);
        
        //Se llama la clase de inicio, que es donde esta la lista global, y se le agrega la nave creada
        Inicio.BD_Naves.add(nuevaNave);
        
        
        //Se pone un mensaje de que se agrego correctamente
        JOptionPane.showMessageDialog(this, "Se guardo la nave " + mNombre + " exitosamente");
        
        
    }
    
    public void Limpiar_Formulario(){
        //Se setean todos los campos como vacios, para no dejar residuos de datos de otras naves ya creadas
        this.F_Nombre.setText("");
        this.F_Tipo_nave.setSelectedItem(null);
        this.F_Tipo_combustible.setText("");
        this.F_Region.setSelectedItem(null);
        this.F_Potencia.setText("");
        this.F_Empuje.setText("");
        this.F_Velocidad.setText("");
        this.F_Peso.setText("");
        this.F_Destino.setSelectedItem(null);
        this.F_Tipo_mision.setSelectedItem(null);
        this.F_Capacidad.setText("");
    
    
}
    
    
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        F_Nombre = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        F_Tipo_combustible = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        F_Potencia = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        F_Empuje = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        F_Velocidad = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        F_Peso = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        F_Capacidad = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        F_Tipo_nave = new javax.swing.JComboBox<>();
        F_Region = new javax.swing.JComboBox<>();
        F_Destino = new javax.swing.JComboBox<>();
        F_Tipo_mision = new javax.swing.JComboBox<>();
        But_Guardar = new javax.swing.JButton();
        But_Limpiar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(153, 0, 255));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel2.setBackground(new java.awt.Color(153, 153, 255));

        jLabel1.setFont(new java.awt.Font("Verdana", 1, 36)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Crear Nueva Nave");

        jLabel2.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel2.setText("Nombre:");

        F_Nombre.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel3.setText("Tipo de nave:");

        jLabel4.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel4.setText("Combustible:");

        F_Tipo_combustible.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel5.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel5.setText("Región:");

        jLabel6.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel6.setText("Potencia:");

        F_Potencia.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel7.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel7.setText("Empuje:");

        F_Empuje.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel8.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel8.setText("Velocidad:");

        F_Velocidad.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel9.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel9.setText("Peso:");

        F_Peso.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel10.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel10.setText("Destino:");

        jLabel11.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel11.setText("Tipo de misión:");

        F_Capacidad.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N

        jLabel12.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        jLabel12.setHorizontalAlignment(javax.swing.SwingConstants.LEFT);
        jLabel12.setText("Capacidad:");

        F_Tipo_nave.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        F_Tipo_nave.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Lanzadera", "Robotica", "Tripulada" }));

        F_Region.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        F_Region.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "EEUU", "Rusia", "Ucrania", "Europa", "China", "Japón", "Internacional" }));

        F_Destino.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        F_Destino.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No definida", "Mercurio", "Venus", "Orbita terrestre", "Luna", "Marte", "Jupiter", "Saturno", "Urano", "Neptuno", "Pluton" }));

        F_Tipo_mision.setFont(new java.awt.Font("Verdana", 0, 18)); // NOI18N
        F_Tipo_mision.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "No definida", "Mision Lunar", "Estudio condiciones ingrávidas", "Estudio humano en exterior de capsula", "Mantenimiento", "Pruebas de equipos" }));

        But_Guardar.setBackground(new java.awt.Color(51, 51, 255));
        But_Guardar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        But_Guardar.setText("Guardar");
        But_Guardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_GuardarActionPerformed(evt);
            }
        });

        But_Limpiar.setBackground(new java.awt.Color(51, 51, 255));
        But_Limpiar.setFont(new java.awt.Font("Verdana", 1, 18)); // NOI18N
        But_Limpiar.setText("Limpiar");
        But_Limpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                But_LimpiarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(23, 25, Short.MAX_VALUE)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(F_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 280, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel8, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(F_Nombre)
                                        .addComponent(F_Tipo_nave, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(F_Tipo_combustible)
                                        .addComponent(F_Region, 0, 280, Short.MAX_VALUE)
                                        .addComponent(F_Potencia)
                                        .addComponent(F_Empuje)
                                        .addComponent(F_Velocidad)
                                        .addComponent(F_Peso)))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addComponent(But_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                                    .addComponent(But_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(jPanel2Layout.createSequentialGroup()
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(6, 6, 6)
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(F_Tipo_mision, 0, 0, Short.MAX_VALUE)
                                        .addComponent(F_Capacidad)))))
                        .addGap(0, 11, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F_Nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel3, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(F_Tipo_nave))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F_Tipo_combustible, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F_Region, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F_Potencia, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F_Empuje, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F_Velocidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F_Peso, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(F_Destino, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel11, javax.swing.GroupLayout.DEFAULT_SIZE, 36, Short.MAX_VALUE)
                    .addComponent(F_Tipo_mision))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(F_Capacidad, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(But_Limpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(But_Guardar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void But_LimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_LimpiarActionPerformed

        //Se limpia el formulario al momento de darle click
        this.Limpiar_Formulario();

    }//GEN-LAST:event_But_LimpiarActionPerformed

    private void But_GuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_But_GuardarActionPerformed
        
        //Se obtienen los datos del formulario
        this.obtenerDatos();
        
        //Se crea un iterador para que busque en la lista BD_Naves
        Iterator<Nave> iterador = Inicio.BD_Naves.iterator();
        
        //Se inicializa el auxiliar en 0
        aux = 0;
        
        //Se itera sobre la lista, que esta metida en el iterador
        while(iterador.hasNext()){
            
            //Se va cambiando de registro mientras exista un siguiente
            Nave Naves = iterador.next();
            
            //Si el nombre de la nave ya se encuentra en la lista, se anuncia que ya existe y se pone el auxiliar en 1
            if (Naves.getNombre().equals(mNombre)){
                JOptionPane.showMessageDialog(this, "La nave " + mNombre + " Ya existe en el sistema");
                aux = 1;
            }
        }
        
        //Si el auxiliar no cambio, entonces se guarda la informacion
        if(aux == 0){
            this.guardarDatos();
        }
        
        //Se limpia el formulario
        this.Limpiar_Formulario();
        
        //Se pone el auxiliar en 0 otra vez
        aux = 0;
    }//GEN-LAST:event_But_GuardarActionPerformed

    
    
    /**
     * @param
     * args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CrearNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CrearNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CrearNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CrearNave.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CrearNave().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton But_Guardar;
    private javax.swing.JButton But_Limpiar;
    private javax.swing.JTextField F_Capacidad;
    private javax.swing.JComboBox<String> F_Destino;
    private javax.swing.JTextField F_Empuje;
    private javax.swing.JTextField F_Nombre;
    private javax.swing.JTextField F_Peso;
    private javax.swing.JTextField F_Potencia;
    private javax.swing.JComboBox<String> F_Region;
    private javax.swing.JTextField F_Tipo_combustible;
    private javax.swing.JComboBox<String> F_Tipo_mision;
    private javax.swing.JComboBox<String> F_Tipo_nave;
    private javax.swing.JTextField F_Velocidad;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
